---

default_install_hook_types:
  - commit-msg
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint
        args:
          - --edit
        language: system
        stages:
          - commit-msg

      - id: treefmt
        name: treefmt
        language: system
        entry: treefmt
        files: .*
        stages:
          - pre-commit
