filetype on

set autoindent
set autoread
set backspace=indent,eol,start
set belloff=all
set colorcolumn=80
set complete-=i
set cscopeverbose
set display=lastline
set encoding=utf-8
set fsync
set guicursor=
set hidden
set history=10000
set hlsearch
set incsearch
set langnoremap
set laststatus=2
set nrformats=bin,hex
set number
set relativenumber
set ruler
set scrolloff=4
set showcmd
set sidescroll=1
set smartcase
set smarttab
set switchbuf=uselast
set ttimeoutlen=50
set ttyfast
set updatetime=100
set wildmenu
set wildoptions=pum,tagfile

set nocompatible
set nojoinspaces
set nolangremap
set nostartofline
set nowrap

syntax enable
