#!/usr/bin/env bash

### AUTOSTART ###
$HOME/.scripts/xrandr/dual.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
unclutter &
nitrogen --restore &
pgrep -x picom > /dev/null || picom &

### MONITORS ###
bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 0

### COLORS ###
bspc config normal_border_color "#4C566A"
bspc config active_border_color "#B48EAD"
bspc config focused_border_color "#8FBCBB"
bspc config presel_feedback_color "#ECEFF4"

### GLOBAL ###
bspc config global_ratio 0.5
xsetroot -cursor_name left_ptr #  set default cursor to left_ptr
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config window_gap 4
bspc config border_width 2
