#!/usr/bin/env bash

### AUTOSTART ###
$HOME/.scripts/xrandr/dual.sh &
pgrep -x sxhkd > /dev/null || sxhkd &
unclutter &
nitrogen --restore &
pgrep -x picom > /dev/null || picom &

### MONITORS ###
bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 0

### COLORS ###
bspc config normal_border_color "#2e3440"
bspc config active_border_color "#3b4252"
bspc config focused_border_color "#88c0d0"
bspc config presel_feedback_color "#a3be8c"

### GLOBAL ###
bspc config global_ratio 0.5
xsetroot -cursor_name left_ptr #  set default cursor to left_ptr
xset r rate 250 50 # increase key polling rate
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true
bspc config window_gap 16
bspc config border_width 4
