set -g aggressive-resize on
set -g automatic-rename off
set -g base-index '1'
set -g default-terminal 'tmux-256color'
set -ag terminal-overrides ',xterm-256color*:RGB'
set -g escape-time 10
set -g focus-events on
set -g mode-keys vi
set -g monitor-activity on
set -g pane-base-index '1'
set -g pane-border-lines simple
