[colors.bright]
black   = "#4c566a"
blue    = "#81a1c1"
cyan    = "#8fbcbb"
green   = "#a3be8c"
magenta = "#b48ead"
red     = "#bf616a"
white   = "#eceff4"
yellow  = "#ebcb8b"

[colors.dim]
black   = "#373e4d"
blue    = "#68809a"
cyan    = "#6d96a5"
green   = "#809575"
magenta = "#8c738c"
red     = "#94545d"
white   = "#aeb3bb"
yellow  = "#b29e75"

[colors.footer_bar]
background = "#434c5e"
foreground = "#d8dee9"

[colors.normal]
black   = "#3b4252"
blue    = "#81a1c1"
cyan    = "#88c0d0"
green   = "#a3be8c"
magenta = "#b48ead"
red     = "#bf616a"
white   = "#e5e9f0"
yellow  = "#ebcb8b"

[colors.primary]
background     = "#2e3440"
dim_foreground = "#a5abb6"
foreground     = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellForeground"

[colors.selection]
background = "#4c566a"
text       = "CellBackground"

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Fira Code Nerd Font"

[font.bold_italic]
family = "Fira Code Nerd Font"

[font.italic]
family = "Fira Code Nerd Font"

[font.normal]
family = "Fira Code Nerd Font"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key    = "PageUp"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key    = "PageDown"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key    = "Home"
mods   = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
multiplier = 2

[window]
dynamic_padding = true
